### PR TITLE
fix FileDescriptor#buildFrom

### PR DESCRIPTION
**Pull request by xuwei-k**
- https://github.com/google/protobuf/blob/v2.6.1/java/src/main/java/com/google/protobuf/Descriptors.java#L233
- https://github.com/google/protobuf/blob/v3.0.0-beta-2/java/src/main/java/com/google/protobuf/Descriptors.java#L255

fix https://github.com/trueaccord/ScalaPB/issues/98

### CODE REVIEW

**Comment by ngbinh** [comment]
thanks @xuwei-k and @thesamet , can you release a new version with the fix? Thanks

**Comment by thesamet** [comment]
Released 0.1.7 of protobuf-scala-runtime. I also published ScalaPB 0.5.24 which depends on it.

**Comment by ngbinh** [comment]
awesome! Thanks a lot!

**Comment by ngbinh** [comment]
still haven't seen `0.5.24` yet http://mvnrepository.com/artifact/com.trueaccord.scalapb/scalapb-runtime_2.11

**Comment by thesamet** [comment]
The web UI can be a little behind, it's definitely already on central: http://central.maven.org/maven2/com/trueaccord/scalapb/scalapb-runtime_2.11/

**Comment by ngbinh** [comment]
looks like the plugin: http://central.maven.org/maven2/com/trueaccord/scalapb/sbt-scalapb_2.10_0.13/ is not there yet. Not sure if it is published separately?

**Comment by thesamet** [comment]
It is published separately - checking.

On Fri, Apr 1, 2016 at 10:45 AM, Binh Nguyen <notifications@github.com>
wrote:

> looks like the plugin:
> http://central.maven.org/maven2/com/trueaccord/scalapb/sbt-scalapb_2.10_0.13/
> is not there yet. Not sure if it is published separately?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/trueaccord/protobuf-scala-runtime/pull/5#issuecomment-204486357>
>



-- 
-Nadav

**Comment by ngbinh** [comment]
got it now, thanks again!

**Pull request merged**
